# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.9.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.9.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/guyjacubovski/dev/live-transcoder

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/guyjacubovski/dev/live-transcoder

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.9.0/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.9.0/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/guyjacubovski/dev/live-transcoder/CMakeFiles /Users/guyjacubovski/dev/live-transcoder/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/guyjacubovski/dev/live-transcoder/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named transcoder

# Build rule for target.
transcoder: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 transcoder
.PHONY : transcoder

# fast build rule for target.
transcoder/fast:
	$(MAKE) -f CMakeFiles/transcoder.dir/build.make CMakeFiles/transcoder.dir/build
.PHONY : transcoder/fast

FramesStats.o: FramesStats.c.o

.PHONY : FramesStats.o

# target to build an object file
FramesStats.c.o:
	$(MAKE) -f CMakeFiles/transcoder.dir/build.make CMakeFiles/transcoder.dir/FramesStats.c.o
.PHONY : FramesStats.c.o

FramesStats.i: FramesStats.c.i

.PHONY : FramesStats.i

# target to preprocess a source file
FramesStats.c.i:
	$(MAKE) -f CMakeFiles/transcoder.dir/build.make CMakeFiles/transcoder.dir/FramesStats.c.i
.PHONY : FramesStats.c.i

FramesStats.s: FramesStats.c.s

.PHONY : FramesStats.s

# target to generate assembly for a file
FramesStats.c.s:
	$(MAKE) -f CMakeFiles/transcoder.dir/build.make CMakeFiles/transcoder.dir/FramesStats.c.s
.PHONY : FramesStats.c.s

TranscodePipeline.o: TranscodePipeline.c.o

.PHONY : TranscodePipeline.o

# target to build an object file
TranscodePipeline.c.o:
	$(MAKE) -f CMakeFiles/transcoder.dir/build.make CMakeFiles/transcoder.dir/TranscodePipeline.c.o
.PHONY : TranscodePipeline.c.o

TranscodePipeline.i: TranscodePipeline.c.i

.PHONY : TranscodePipeline.i

# target to preprocess a source file
TranscodePipeline.c.i:
	$(MAKE) -f CMakeFiles/transcoder.dir/build.make CMakeFiles/transcoder.dir/TranscodePipeline.c.i
.PHONY : TranscodePipeline.c.i

TranscodePipeline.s: TranscodePipeline.c.s

.PHONY : TranscodePipeline.s

# target to generate assembly for a file
TranscodePipeline.c.s:
	$(MAKE) -f CMakeFiles/transcoder.dir/build.make CMakeFiles/transcoder.dir/TranscodePipeline.c.s
.PHONY : TranscodePipeline.c.s

codec.o: codec.c.o

.PHONY : codec.o

# target to build an object file
codec.c.o:
	$(MAKE) -f CMakeFiles/transcoder.dir/build.make CMakeFiles/transcoder.dir/codec.c.o
.PHONY : codec.c.o

codec.i: codec.c.i

.PHONY : codec.i

# target to preprocess a source file
codec.c.i:
	$(MAKE) -f CMakeFiles/transcoder.dir/build.make CMakeFiles/transcoder.dir/codec.c.i
.PHONY : codec.c.i

codec.s: codec.c.s

.PHONY : codec.s

# target to generate assembly for a file
codec.c.s:
	$(MAKE) -f CMakeFiles/transcoder.dir/build.make CMakeFiles/transcoder.dir/codec.c.s
.PHONY : codec.c.s

config.o: config.c.o

.PHONY : config.o

# target to build an object file
config.c.o:
	$(MAKE) -f CMakeFiles/transcoder.dir/build.make CMakeFiles/transcoder.dir/config.c.o
.PHONY : config.c.o

config.i: config.c.i

.PHONY : config.i

# target to preprocess a source file
config.c.i:
	$(MAKE) -f CMakeFiles/transcoder.dir/build.make CMakeFiles/transcoder.dir/config.c.i
.PHONY : config.c.i

config.s: config.c.s

.PHONY : config.s

# target to generate assembly for a file
config.c.s:
	$(MAKE) -f CMakeFiles/transcoder.dir/build.make CMakeFiles/transcoder.dir/config.c.s
.PHONY : config.c.s

filter.o: filter.c.o

.PHONY : filter.o

# target to build an object file
filter.c.o:
	$(MAKE) -f CMakeFiles/transcoder.dir/build.make CMakeFiles/transcoder.dir/filter.c.o
.PHONY : filter.c.o

filter.i: filter.c.i

.PHONY : filter.i

# target to preprocess a source file
filter.c.i:
	$(MAKE) -f CMakeFiles/transcoder.dir/build.make CMakeFiles/transcoder.dir/filter.c.i
.PHONY : filter.c.i

filter.s: filter.c.s

.PHONY : filter.s

# target to generate assembly for a file
filter.c.s:
	$(MAKE) -f CMakeFiles/transcoder.dir/build.make CMakeFiles/transcoder.dir/filter.c.s
.PHONY : filter.c.s

json_parser.o: json_parser.c.o

.PHONY : json_parser.o

# target to build an object file
json_parser.c.o:
	$(MAKE) -f CMakeFiles/transcoder.dir/build.make CMakeFiles/transcoder.dir/json_parser.c.o
.PHONY : json_parser.c.o

json_parser.i: json_parser.c.i

.PHONY : json_parser.i

# target to preprocess a source file
json_parser.c.i:
	$(MAKE) -f CMakeFiles/transcoder.dir/build.make CMakeFiles/transcoder.dir/json_parser.c.i
.PHONY : json_parser.c.i

json_parser.s: json_parser.c.s

.PHONY : json_parser.s

# target to generate assembly for a file
json_parser.c.s:
	$(MAKE) -f CMakeFiles/transcoder.dir/build.make CMakeFiles/transcoder.dir/json_parser.c.s
.PHONY : json_parser.c.s

listener.o: listener.c.o

.PHONY : listener.o

# target to build an object file
listener.c.o:
	$(MAKE) -f CMakeFiles/transcoder.dir/build.make CMakeFiles/transcoder.dir/listener.c.o
.PHONY : listener.c.o

listener.i: listener.c.i

.PHONY : listener.i

# target to preprocess a source file
listener.c.i:
	$(MAKE) -f CMakeFiles/transcoder.dir/build.make CMakeFiles/transcoder.dir/listener.c.i
.PHONY : listener.c.i

listener.s: listener.c.s

.PHONY : listener.s

# target to generate assembly for a file
listener.c.s:
	$(MAKE) -f CMakeFiles/transcoder.dir/build.make CMakeFiles/transcoder.dir/listener.c.s
.PHONY : listener.c.s

logger.o: logger.c.o

.PHONY : logger.o

# target to build an object file
logger.c.o:
	$(MAKE) -f CMakeFiles/transcoder.dir/build.make CMakeFiles/transcoder.dir/logger.c.o
.PHONY : logger.c.o

logger.i: logger.c.i

.PHONY : logger.i

# target to preprocess a source file
logger.c.i:
	$(MAKE) -f CMakeFiles/transcoder.dir/build.make CMakeFiles/transcoder.dir/logger.c.i
.PHONY : logger.c.i

logger.s: logger.c.s

.PHONY : logger.s

# target to generate assembly for a file
logger.c.s:
	$(MAKE) -f CMakeFiles/transcoder.dir/build.make CMakeFiles/transcoder.dir/logger.c.s
.PHONY : logger.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/transcoder.dir/build.make CMakeFiles/transcoder.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/transcoder.dir/build.make CMakeFiles/transcoder.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/transcoder.dir/build.make CMakeFiles/transcoder.dir/main.c.s
.PHONY : main.c.s

output.o: output.c.o

.PHONY : output.o

# target to build an object file
output.c.o:
	$(MAKE) -f CMakeFiles/transcoder.dir/build.make CMakeFiles/transcoder.dir/output.c.o
.PHONY : output.c.o

output.i: output.c.i

.PHONY : output.i

# target to preprocess a source file
output.c.i:
	$(MAKE) -f CMakeFiles/transcoder.dir/build.make CMakeFiles/transcoder.dir/output.c.i
.PHONY : output.c.i

output.s: output.c.s

.PHONY : output.s

# target to generate assembly for a file
output.c.s:
	$(MAKE) -f CMakeFiles/transcoder.dir/build.make CMakeFiles/transcoder.dir/output.c.s
.PHONY : output.c.s

utils.o: utils.c.o

.PHONY : utils.o

# target to build an object file
utils.c.o:
	$(MAKE) -f CMakeFiles/transcoder.dir/build.make CMakeFiles/transcoder.dir/utils.c.o
.PHONY : utils.c.o

utils.i: utils.c.i

.PHONY : utils.i

# target to preprocess a source file
utils.c.i:
	$(MAKE) -f CMakeFiles/transcoder.dir/build.make CMakeFiles/transcoder.dir/utils.c.i
.PHONY : utils.c.i

utils.s: utils.c.s

.PHONY : utils.s

# target to generate assembly for a file
utils.c.s:
	$(MAKE) -f CMakeFiles/transcoder.dir/build.make CMakeFiles/transcoder.dir/utils.c.s
.PHONY : utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... transcoder"
	@echo "... FramesStats.o"
	@echo "... FramesStats.i"
	@echo "... FramesStats.s"
	@echo "... TranscodePipeline.o"
	@echo "... TranscodePipeline.i"
	@echo "... TranscodePipeline.s"
	@echo "... codec.o"
	@echo "... codec.i"
	@echo "... codec.s"
	@echo "... config.o"
	@echo "... config.i"
	@echo "... config.s"
	@echo "... filter.o"
	@echo "... filter.i"
	@echo "... filter.s"
	@echo "... json_parser.o"
	@echo "... json_parser.i"
	@echo "... json_parser.s"
	@echo "... listener.o"
	@echo "... listener.i"
	@echo "... listener.s"
	@echo "... logger.o"
	@echo "... logger.i"
	@echo "... logger.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... output.o"
	@echo "... output.i"
	@echo "... output.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

