apiVersion: v1
kind: ConfigMap
metadata:
  name: packagers-config
data:
  nginx.conf: |
    server {
       listen                  9999;
       root                    /usr/share/nginx/html;
       resolver                100.64.0.10;  # fill will the ip address of the KubeDNS
       ssl_verify_client       off;
       location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
       }
       location ~ /m/([^.]+)/p/([^\/]+)/(.*) {
           proxy_set_header Host      $host;   #preserve host name
           proxy_set_header X-Real-IP $remote_addr;   #preserve ip address
           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
           proxy_pass https://$1.rtc.default.svc.cluster.local:$2/$3$is_args$args;
       }
       location = /kube-system/healthz {
         return 200 "Kaltura";
       }
       location = /metrics {
         return 200 "";
       }
        location ~ ^/(.*) {
          return 200 "{}";
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: packagers
spec:
  replicas: 1
  selector:
    matchLabels:
      component: packager
  template:
    metadata:
      labels:
        component: packager
    spec:
      containers:
      - name: packager
        image: nginx:1.13.10-alpine
        ports:
        - name: http
          containerPort: 9999
          hostPort: 9999
        volumeMounts:
        - name: mysite-configs
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
      volumes:
      - name: mysite-configs
        configMap:
          name: packagers-config